# Colors are managed by pywal16
[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[font]
size = 12

# Mono fonts are best suited for terminal use.
[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
y = 2

[window]
decorations = "None"
opacity = 0.9

[window.padding]
x = 4
y = 4
