#!/bin/bash

export DDG_ARGS='["-n", 10]'
export ROFI_SEARCH='ddgr'
export ROFI_SEARCH_CMD='firefox --private-window $URL'

rofi -modi blocks -blocks-wrap /usr/bin/rofi-search -show blocks \
    -lines 4 -eh 4 -kb-custom-1 'Control+y' $@
