vim.keymap.set('n', '<leader>gs', vim.cmd.Git, opts)
vim.keymap.set('n', '<leader>ggp', function() vim.cmd.Git('push') end, opts)
vim.keymap.set('n', '<leader>gpf', function() vim.cmd.Git('push -f') end, opts)
vim.keymap.set('n', '<leader>ggl', function() vim.cmd.Git('pull') end, opts)
vim.keymap.set('n', '<leader>gcob', ':G checkout -b ', opts)
--vim.keymap.set('n', '<leader>gpu', ':G push -u origin <C-R>=GetCurrentBranch()<CR><CR>', opts)
