so $XDG_CONFIG_HOME/vim/xdg-support.vim
so $XDG_CONFIG_HOME/vim/basic.vim
so $XDG_CONFIG_HOME/vim/plugins.vim

"let g:gruvbox_invert_selection='0'
":silent! colorscheme gruvbox

let g:nord_italic = 1
let g:nord_italic_comments = 1
:silent! colorscheme nord

"set background=dark

" Needed for Nord theme to maintain solid background while
" the terminal emulator has background transparency
if (has("termguicolors"))
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

if executable('rg')
    let g:rg_derive_root='true'
endif

let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let mapleader=" "
let g:netrw_browse_split = 4 " Open in previous window
let g:netrw_banner = 0
let g:netrw_liststyle = 3 " hierarchical style
let g:netrw_winsize = 25

" ag is fast enought that CtrlP doesn't need to cache
let g:ctrlp_use_caching = 0

so $XDG_CONFIG_HOME/vim/mappings.vim
