#!/bin/sh

tmux new-session \; \
  send-keys 'btop' C-m \; \
  split-window -h \; \
  split-window -h \; \
  select-pane -t 1 \; \
  split-window -v \; \
  send-keys 'ff' C-m \; \
  select-layout -E \; \
  select-pane -t 3 \;
